# -------------------------------------------------------------------
# システムコンテキスト定義書：補助金・助成金情報 Twitter自動投稿システム
# バージョン: 1.0
# 作成日: 2025-07-06
# -------------------------------------------------------------------
apiVersion: v1.0
kind: SystemContextDefinition
metadata:
  name: "補助金・助成金情報 Twitter自動投稿システム"
  projectName: "HatoLink" # プロジェクト名

spec:
  backgroundAndPurpose:
    background: |
      現在、スクレイピングにより収集した補助金・助成金情報を週次で集計し、Excelで管理、メルマガで配信する業務フローが存在する。
      この情報提供サービスは、週に数千件という膨大な情報量を扱っている。
    challengesAndOpportunities:
      - title: "リーチの限界"
        description: "主要な情報発信チャネルがメルマガに限定されており、より広く、多様な層へのリーチ拡大に課題がある。"
      - title: "即時性の欠如"
        description: "週次のメルマガ配信では、情報の鮮度が落ち、公募期間の短い案件などをタイムリーに届けられない機会損失が発生している。"
      - title: "手動運用の限界"
        description: "数千件に及ぶ情報をTwitterなどのリアルタイムメディアで発信しようにも、手動での投稿は非現実的であり、工数と人為的ミスの観点から自動化が不可欠である。"
    objective: |
      本システムは、既存の情報収集プロセスと連携し、補助金・助成金に関する大量の情報をTwitterへ自動的に投稿することを目的とする。
      これにより、情報発信の効率性と即時性を飛躍的に向上させ、サービスのリーチを最大化し、情報プラットフォームとしての価値を高める。

  valueProposition:
    forBusinessAndOperators:
      - "圧倒的な業務効率化: Twitterへの投稿作業を完全に自動化し、運用工数をゼロに近づける。"
      - "リーチ拡大と新規顧客獲得: Twitterの拡散力を活用し、これまでアプローチできなかった新しいユーザー層へ情報を届ける。"
      - "サービス価値の向上: 情報の即時性を高めることで、ユーザー満足度を向上させ、競合サービスに対する優位性を確立する。"
      - "計画的な情報発信: 予約投稿機能により、戦略的かつ継続的な情報配信が可能になる。"
    forEndUsers:
      - "機会損失の防止: 公募開始直後の新鮮な補助金・助成金情報をリアルタイムに近い形で入手できる。"

  stakeholders:
    actors:
      - role: "コンテンツ管理者"
        description: "本システムの主たる運用者。"
        responsibilities:
          - "投稿するツイート群を所定のフォーマットで準備し、システムへ一括アップロードする。"
          - "緊急の案件や修正が必要なツイートを、管理画面から個別に登録・編集・削除する。"
      - role: "自動投稿エンジン (本システム/Google Apps Script)"
        description: "システムのコアとなる自動実行コンポーネント。"
        responsibilities:
          - "定められたスケジュールに基づき、Googleスプレッドシート上の投稿キューを監視する。"
          - "投稿予定時刻を過ぎた未投稿ツイートを検知し、Twitter APIを介して自動的に投稿を実行する。"
      - role: "(将来像) 外部連携システム"
        description: "APIを介して、本システムに投稿データを自動的に登録する、既存または新規の別システム。"
    otherStakeholders:
      - role: "事業責任者"
        description: "システム投資対効果（リーチ拡大、ブランド認知度向上、将来的な収益化）に責任を持つ。"
      - role: "情報収集担当者"
        description: "スクレイピングなど、本システムへのインプットとなる情報を生成する担当者。"
      - role: "Twitterフォロワー / メルマガ読者"
        description: "情報の最終的な受け手。"

  systemScopeAndResponsibilities:
    keyFeatures:
      - name: "ツイート投稿管理機能"
        description: "Googleスプレッドシートをデータベースとして利用し、ツイート内容、投稿予約日時、投稿ステータス（未投稿/投稿済/エラー）、投稿完了日時などを一元管理する。"
      - name: "予約自動投稿機能"
        description: "定期的にスプレッドシートをチェックし、投稿予約時刻を過ぎた「未投稿」ステータスのツイートを自動でTwitterに投稿する。"
      - name: "データ一括登録機能"
        description: "管理者が所定のフォーマットのスプレッドシート（旧Excelに相当）を管理画面からアップロードすることで、大量のツイート予約を一括で登録する。"
      - name: "データ個別操作機能"
        description: "管理画面を通じて、ツイートを一件ずつ手動で登録、編集、削除する。"
      - name: "(将来拡張) API連携機能"
        description: "外部システムからのデータ登録（一括・個別）を可能にするためのAPIを提供する。"
    scope:
      inScope:
        - "投稿用データの受付（アップロード、個別登録、API経由）"
        - "投稿スケジュールの管理と、それに基づいたTwitterへの自動投稿"
        - "投稿結果（成功/失敗）のステータス管理"
        - "初期開発はGoogleスプレッドシートとGoogle Apps Scriptを技術基盤とすること"
      outOfScope:
        - "情報収集: 元となる補助金・助成金情報のスクレイピングや収集"
        - "ツイート文の生成: 投稿するツイートの文章作成そのもの"
        - "インタラクション管理: 投稿後の「いいね」やリプライ、DMへの対応"
        - "効果測定・分析: 投稿のインプレッションやエンゲージメント等の詳細な分析"

  keyElementsAndConstraints:
    majorData:
      - name: "投稿管理ID"
        description: "各ツイートを一意に識別するID。"
      - name: "ツイート本文"
        description: "投稿するテキスト。"
      - name: "投稿予約日時"
        description: "投稿を希望する日時。"
      - name: "投稿ステータス"
        description: "「未投稿」「投稿済」「エラー」など。"
      - name: "投稿完了日時"
        description: "実際に投稿が完了した日時。"
    constraintsAndAssumptions:
      - category: "技術選定"
        description: "初期フェーズではGoogle Workspace (Googleスプレッドシート, Google Apps Script) を全面的に採用し、迅速かつ低コストでの開発を目指す。"
      - category: "API利用"
        description: "Twitter APIの利用規約、特にツイート投稿数に関するレートリミット（上限）を遵守した設計が必要となる。API認証情報はセキュアに管理する。"
      - category: "データフォーマット"
        description: "一括アップロード機能で利用するスプレッドシートの列構成やデータ形式は、厳密に規定する必要がある。"
      - category: "開発アプローチ"
        description: "段階的開発を採用し、まずは中核機能である「スプレッドシートからの自動投稿」を確立し、その後「管理画面」「API連携」といった機能を開発していく。"